version: 2.1
orbs:
  ruby: circleci/ruby@2.1.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake
workflows:
  version: 2
  deploy:
    jobs:
      - test