version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.4.7-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake
workflows:
  version: 2
  deploy:
    jobs:
      - test